{{- if and .Values.metrics.service.enabled .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "nificontrol.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nificontrol.labels" . | nindent 4 }}
    {{- with .Values.metrics.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "nificontrol.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      path: {{ .Values.metrics.serviceMonitor.path | default "/metrics" }}
      scheme: http
      {{- with .Values.metrics.serviceMonitor.interval }}
      interval: {{ . | quote }}
      {{- end }}
      {{- with .Values.metrics.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ . | quote }}
      {{- end }}
{{- end }}
