resources:
  - nifi_v1alpha1_nificluster.yaml
  - nifi_v1alpha1_nifiregistryclient.yaml
  - nifi_v1alpha1_nifiparametercontext.yaml
  - nifi_v1alpha1_nifiuser.yaml
  - nifi_v1alpha1_nifiusergroup.yaml
  - nifi_v1alpha1_nifiprocessgroup.yaml
  - nifi_v1alpha1_nificontrollerservice.yaml
  - nifi_v1alpha1_nififlowbundle.yaml
  - nifi_v1alpha1_nififlowdeployment.yaml
  - nifi_v1alpha1_nifiprocessor.yaml
  - nifi_v1alpha1_nifiinputport.yaml
  - nifi_v1alpha1_nifioutputport.yaml
  - nifi_v1alpha1_nificonnection.yaml
  - nifi_v1alpha1_nifireportingtask.yaml
  - nifi_v1alpha1_nififunnel.yaml
  - nifi_v1alpha1_nifilabel.yaml
