apiVersion: nifi.controlnifi.io/v1alpha1
kind: NiFiCluster
metadata:
  name: production
spec:
  mode: Internal
  image: apache/nifi:2.0.0
  replicas: 3
  deletionPolicy: Orphan
  driftPolicy:
    mode: Warn
