//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdoptionPolicy) DeepCopyInto(out *AdoptionPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdoptionPolicy.
func (in *AdoptionPolicy) DeepCopy() *AdoptionPolicy {
	if in == nil {
		return nil
	}
	out := new(AdoptionPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterReference) DeepCopyInto(out *ClusterReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterReference.
func (in *ClusterReference) DeepCopy() *ClusterReference {
	if in == nil {
		return nil
	}
	out := new(ClusterReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommonStatus) DeepCopyInto(out *CommonStatus) {
	*out = *in
	out.Revision = in.Revision
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Dependencies.DeepCopyInto(&out.Dependencies)
	in.Drift.DeepCopyInto(&out.Drift)
	in.Sync.DeepCopyInto(&out.Sync)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommonStatus.
func (in *CommonStatus) DeepCopy() *CommonStatus {
	if in == nil {
		return nil
	}
	out := new(CommonStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentBundle) DeepCopyInto(out *ComponentBundle) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentBundle.
func (in *ComponentBundle) DeepCopy() *ComponentBundle {
	if in == nil {
		return nil
	}
	out := new(ComponentBundle)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentScheduling) DeepCopyInto(out *ComponentScheduling) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentScheduling.
func (in *ComponentScheduling) DeepCopy() *ComponentScheduling {
	if in == nil {
		return nil
	}
	out := new(ComponentScheduling)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DependencyStatus) DeepCopyInto(out *DependencyStatus) {
	*out = *in
	if in.WaitingFor != nil {
		in, out := &in.WaitingFor, &out.WaitingFor
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DependencyStatus.
func (in *DependencyStatus) DeepCopy() *DependencyStatus {
	if in == nil {
		return nil
	}
	out := new(DependencyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DriftPolicy) DeepCopyInto(out *DriftPolicy) {
	*out = *in
	if in.IgnoreFields != nil {
		in, out := &in.IgnoreFields, &out.IgnoreFields
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DriftPolicy.
func (in *DriftPolicy) DeepCopy() *DriftPolicy {
	if in == nil {
		return nil
	}
	out := new(DriftPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DriftStatus) DeepCopyInto(out *DriftStatus) {
	*out = *in
	if in.LastDetectedTime != nil {
		in, out := &in.LastDetectedTime, &out.LastDetectedTime
		*out = (*in).DeepCopy()
	}
	if in.Differences != nil {
		in, out := &in.Differences, &out.Differences
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DriftStatus.
func (in *DriftStatus) DeepCopy() *DriftStatus {
	if in == nil {
		return nil
	}
	out := new(DriftStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlowBundleSource) DeepCopyInto(out *FlowBundleSource) {
	*out = *in
	if in.Git != nil {
		in, out := &in.Git, &out.Git
		*out = new(GitSource)
		**out = **in
	}
	if in.OCI != nil {
		in, out := &in.OCI, &out.OCI
		*out = new(OCISource)
		**out = **in
	}
	if in.Registry != nil {
		in, out := &in.Registry, &out.Registry
		*out = new(RegistryFlowSource)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlowBundleSource.
func (in *FlowBundleSource) DeepCopy() *FlowBundleSource {
	if in == nil {
		return nil
	}
	out := new(FlowBundleSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlowDeploymentSource) DeepCopyInto(out *FlowDeploymentSource) {
	*out = *in
	if in.BundleRef != nil {
		in, out := &in.BundleRef, &out.BundleRef
		*out = new(LocalObjectReference)
		**out = **in
	}
	if in.Inline != nil {
		in, out := &in.Inline, &out.Inline
		*out = new(FlowBundleSource)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlowDeploymentSource.
func (in *FlowDeploymentSource) DeepCopy() *FlowDeploymentSource {
	if in == nil {
		return nil
	}
	out := new(FlowDeploymentSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlowDeploymentTarget) DeepCopyInto(out *FlowDeploymentTarget) {
	*out = *in
	out.ParentProcessGroupRef = in.ParentProcessGroupRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlowDeploymentTarget.
func (in *FlowDeploymentTarget) DeepCopy() *FlowDeploymentTarget {
	if in == nil {
		return nil
	}
	out := new(FlowDeploymentTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitSource) DeepCopyInto(out *GitSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitSource.
func (in *GitSource) DeepCopy() *GitSource {
	if in == nil {
		return nil
	}
	out := new(GitSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalObjectReference) DeepCopyInto(out *LocalObjectReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalObjectReference.
func (in *LocalObjectReference) DeepCopy() *LocalObjectReference {
	if in == nil {
		return nil
	}
	out := new(LocalObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NiFiCluster) DeepCopyInto(out *NiFiCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NiFiCluster.
func (in *NiFiCluster) DeepCopy() *NiFiCluster {
	if in == nil {
		return nil
	}
	out := new(NiFiCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NiFiCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NiFiClusterAPISpec) DeepCopyInto(out *NiFiClusterAPISpec) {
	*out = *in
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NiFiClusterAPISpec.
func (in *NiFiClusterAPISpec) DeepCopy() *NiFiClusterAPISpec {
	if in == nil {
		return nil
	}
	out := new(NiFiClusterAPISpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NiFiClusterList) DeepCopyInto(out *NiFiClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NiFiCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NiFiClusterList.
func (in *NiFiClusterList) DeepCopy() *NiFiClusterList {
	if in == nil {
		return nil
	}
	out := new(NiFiClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NiFiClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NiFiClusterSpec) DeepCopyInto(out *NiFiClusterSpec) {
	*out = *in
	if in.API != nil {
		in, out := &in.API, &out.API
		*out = new(NiFiClusterAPISpec)
		(*in).DeepCopyInto(*out)
	}
	in.DriftPolicy.DeepCopyInto(&out.DriftPolicy)
	out.AdoptionPolicy = in.AdoptionPolicy
	out.Reconciliation = in.Reconciliation
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NiFiClusterSpec.
func (in *NiFiClusterSpec) DeepCopy() *NiFiClusterSpec {
	if in == nil {
		return nil
	}
	out := new(NiFiClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NiFiClusterStatus) DeepCopyInto(out *NiFiClusterStatus) {
	*out = *in
	in.CommonStatus.DeepCopyInto(&out.CommonStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NiFiClusterStatus.
func (in *NiFiClusterStatus) DeepCopy() *NiFiClusterStatus {
	if in == nil {
		return nil
	}
	out := new(NiFiClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NiFiControllerService) DeepCopyInto(out *NiFiControllerService) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NiFiControllerService.
func (in *NiFiControllerService) DeepCopy() *NiFiControllerService {
	if in == nil {
		return nil
	}
	out := new(NiFiControllerService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NiFiControllerService) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NiFiControllerServiceList) DeepCopyInto(out *NiFiControllerServiceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NiFiControllerService, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NiFiControllerServiceList.
func (in *NiFiControllerServiceList) DeepCopy() *NiFiControllerServiceList {
	if in == nil {
		return nil
	}
	out := new(NiFiControllerServiceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NiFiControllerServiceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NiFiControllerServiceSpec) DeepCopyInto(out *NiFiControllerServiceSpec) {
	*out = *in
	out.ClusterRef = in.ClusterRef
	out.ParentProcessGroupRef = in.ParentProcessGroupRef
	if in.Bundle != nil {
		in, out := &in.Bundle, &out.Bundle
		*out = new(ComponentBundle)
		**out = **in
	}
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.SensitiveProperties != nil {
		in, out := &in.SensitiveProperties, &out.SensitiveProperties
		*out = make(map[string]SensitivePropertySource, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.ParameterContextRef != nil {
		in, out := &in.ParameterContextRef, &out.ParameterContextRef
		*out = new(LocalObjectReference)
		**out = **in
	}
	in.DriftPolicy.DeepCopyInto(&out.DriftPolicy)
	out.AdoptionPolicy = in.AdoptionPolicy
	out.Reconciliation = in.Reconciliation
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NiFiControllerServiceSpec.
func (in *NiFiControllerServiceSpec) DeepCopy() *NiFiControllerServiceSpec {
	if in == nil {
		return nil
	}
	out := new(NiFiControllerServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NiFiControllerServiceStatus) DeepCopyInto(out *NiFiControllerServiceStatus) {
	*out = *in
	in.CommonStatus.DeepCopyInto(&out.CommonStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NiFiControllerServiceStatus.
func (in *NiFiControllerServiceStatus) DeepCopy() *NiFiControllerServiceStatus {
	if in == nil {
		return nil
	}
	out := new(NiFiControllerServiceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NiFiFlowBundle) DeepCopyInto(out *NiFiFlowBundle) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NiFiFlowBundle.
func (in *NiFiFlowBundle) DeepCopy() *NiFiFlowBundle {
	if in == nil {
		return nil
	}
	out := new(NiFiFlowBundle)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NiFiFlowBundle) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NiFiFlowBundleList) DeepCopyInto(out *NiFiFlowBundleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NiFiFlowBundle, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NiFiFlowBundleList.
func (in *NiFiFlowBundleList) DeepCopy() *NiFiFlowBundleList {
	if in == nil {
		return nil
	}
	out := new(NiFiFlowBundleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NiFiFlowBundleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NiFiFlowBundleSpec) DeepCopyInto(out *NiFiFlowBundleSpec) {
	*out = *in
	in.Source.DeepCopyInto(&out.Source)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NiFiFlowBundleSpec.
func (in *NiFiFlowBundleSpec) DeepCopy() *NiFiFlowBundleSpec {
	if in == nil {
		return nil
	}
	out := new(NiFiFlowBundleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NiFiFlowBundleStatus) DeepCopyInto(out *NiFiFlowBundleStatus) {
	*out = *in
	in.CommonStatus.DeepCopyInto(&out.CommonStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NiFiFlowBundleStatus.
func (in *NiFiFlowBundleStatus) DeepCopy() *NiFiFlowBundleStatus {
	if in == nil {
		return nil
	}
	out := new(NiFiFlowBundleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NiFiFlowDeployment) DeepCopyInto(out *NiFiFlowDeployment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NiFiFlowDeployment.
func (in *NiFiFlowDeployment) DeepCopy() *NiFiFlowDeployment {
	if in == nil {
		return nil
	}
	out := new(NiFiFlowDeployment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NiFiFlowDeployment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NiFiFlowDeploymentList) DeepCopyInto(out *NiFiFlowDeploymentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NiFiFlowDeployment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NiFiFlowDeploymentList.
func (in *NiFiFlowDeploymentList) DeepCopy() *NiFiFlowDeploymentList {
	if in == nil {
		return nil
	}
	out := new(NiFiFlowDeploymentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NiFiFlowDeploymentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NiFiFlowDeploymentSpec) DeepCopyInto(out *NiFiFlowDeploymentSpec) {
	*out = *in
	out.ClusterRef = in.ClusterRef
	in.Source.DeepCopyInto(&out.Source)
	out.Target = in.Target
	if in.ParameterContextRef != nil {
		in, out := &in.ParameterContextRef, &out.ParameterContextRef
		*out = new(LocalObjectReference)
		**out = **in
	}
	out.Rollout = in.Rollout
	out.Rollback = in.Rollback
	out.Ownership = in.Ownership
	in.DriftPolicy.DeepCopyInto(&out.DriftPolicy)
	out.AdoptionPolicy = in.AdoptionPolicy
	out.Reconciliation = in.Reconciliation
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NiFiFlowDeploymentSpec.
func (in *NiFiFlowDeploymentSpec) DeepCopy() *NiFiFlowDeploymentSpec {
	if in == nil {
		return nil
	}
	out := new(NiFiFlowDeploymentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NiFiFlowDeploymentStatus) DeepCopyInto(out *NiFiFlowDeploymentStatus) {
	*out = *in
	in.CommonStatus.DeepCopyInto(&out.CommonStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NiFiFlowDeploymentStatus.
func (in *NiFiFlowDeploymentStatus) DeepCopy() *NiFiFlowDeploymentStatus {
	if in == nil {
		return nil
	}
	out := new(NiFiFlowDeploymentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NiFiParameterContext) DeepCopyInto(out *NiFiParameterContext) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NiFiParameterContext.
func (in *NiFiParameterContext) DeepCopy() *NiFiParameterContext {
	if in == nil {
		return nil
	}
	out := new(NiFiParameterContext)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NiFiParameterContext) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NiFiParameterContextList) DeepCopyInto(out *NiFiParameterContextList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NiFiParameterContext, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NiFiParameterContextList.
func (in *NiFiParameterContextList) DeepCopy() *NiFiParameterContextList {
	if in == nil {
		return nil
	}
	out := new(NiFiParameterContextList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NiFiParameterContextList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NiFiParameterContextSpec) DeepCopyInto(out *NiFiParameterContextSpec) {
	*out = *in
	out.ClusterRef = in.ClusterRef
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make([]Parameter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.InheritedRefs != nil {
		in, out := &in.InheritedRefs, &out.InheritedRefs
		*out = make([]LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	in.DriftPolicy.DeepCopyInto(&out.DriftPolicy)
	out.AdoptionPolicy = in.AdoptionPolicy
	out.Reconciliation = in.Reconciliation
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NiFiParameterContextSpec.
func (in *NiFiParameterContextSpec) DeepCopy() *NiFiParameterContextSpec {
	if in == nil {
		return nil
	}
	out := new(NiFiParameterContextSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NiFiParameterContextStatus) DeepCopyInto(out *NiFiParameterContextStatus) {
	*out = *in
	in.CommonStatus.DeepCopyInto(&out.CommonStatus)
	if in.LatestUpdateRequest != nil {
		in, out := &in.LatestUpdateRequest, &out.LatestUpdateRequest
		*out = new(ParameterContextUpdateRequestStatus)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NiFiParameterContextStatus.
func (in *NiFiParameterContextStatus) DeepCopy() *NiFiParameterContextStatus {
	if in == nil {
		return nil
	}
	out := new(NiFiParameterContextStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NiFiProcessGroup) DeepCopyInto(out *NiFiProcessGroup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NiFiProcessGroup.
func (in *NiFiProcessGroup) DeepCopy() *NiFiProcessGroup {
	if in == nil {
		return nil
	}
	out := new(NiFiProcessGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NiFiProcessGroup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NiFiProcessGroupList) DeepCopyInto(out *NiFiProcessGroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NiFiProcessGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NiFiProcessGroupList.
func (in *NiFiProcessGroupList) DeepCopy() *NiFiProcessGroupList {
	if in == nil {
		return nil
	}
	out := new(NiFiProcessGroupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NiFiProcessGroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NiFiProcessGroupSpec) DeepCopyInto(out *NiFiProcessGroupSpec) {
	*out = *in
	out.ClusterRef = in.ClusterRef
	out.ParentProcessGroupRef = in.ParentProcessGroupRef
	if in.Position != nil {
		in, out := &in.Position, &out.Position
		*out = new(Position)
		**out = **in
	}
	if in.ParameterContextRef != nil {
		in, out := &in.ParameterContextRef, &out.ParameterContextRef
		*out = new(LocalObjectReference)
		**out = **in
	}
	in.DriftPolicy.DeepCopyInto(&out.DriftPolicy)
	out.AdoptionPolicy = in.AdoptionPolicy
	out.Reconciliation = in.Reconciliation
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NiFiProcessGroupSpec.
func (in *NiFiProcessGroupSpec) DeepCopy() *NiFiProcessGroupSpec {
	if in == nil {
		return nil
	}
	out := new(NiFiProcessGroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NiFiProcessGroupStatus) DeepCopyInto(out *NiFiProcessGroupStatus) {
	*out = *in
	in.CommonStatus.DeepCopyInto(&out.CommonStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NiFiProcessGroupStatus.
func (in *NiFiProcessGroupStatus) DeepCopy() *NiFiProcessGroupStatus {
	if in == nil {
		return nil
	}
	out := new(NiFiProcessGroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NiFiRegistryClient) DeepCopyInto(out *NiFiRegistryClient) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NiFiRegistryClient.
func (in *NiFiRegistryClient) DeepCopy() *NiFiRegistryClient {
	if in == nil {
		return nil
	}
	out := new(NiFiRegistryClient)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NiFiRegistryClient) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NiFiRegistryClientList) DeepCopyInto(out *NiFiRegistryClientList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NiFiRegistryClient, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NiFiRegistryClientList.
func (in *NiFiRegistryClientList) DeepCopy() *NiFiRegistryClientList {
	if in == nil {
		return nil
	}
	out := new(NiFiRegistryClientList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NiFiRegistryClientList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NiFiRegistryClientSpec) DeepCopyInto(out *NiFiRegistryClientSpec) {
	*out = *in
	out.ClusterRef = in.ClusterRef
	in.DriftPolicy.DeepCopyInto(&out.DriftPolicy)
	out.AdoptionPolicy = in.AdoptionPolicy
	out.Reconciliation = in.Reconciliation
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NiFiRegistryClientSpec.
func (in *NiFiRegistryClientSpec) DeepCopy() *NiFiRegistryClientSpec {
	if in == nil {
		return nil
	}
	out := new(NiFiRegistryClientSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NiFiRegistryClientStatus) DeepCopyInto(out *NiFiRegistryClientStatus) {
	*out = *in
	in.CommonStatus.DeepCopyInto(&out.CommonStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NiFiRegistryClientStatus.
func (in *NiFiRegistryClientStatus) DeepCopy() *NiFiRegistryClientStatus {
	if in == nil {
		return nil
	}
	out := new(NiFiRegistryClientStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NiFiUser) DeepCopyInto(out *NiFiUser) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NiFiUser.
func (in *NiFiUser) DeepCopy() *NiFiUser {
	if in == nil {
		return nil
	}
	out := new(NiFiUser)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NiFiUser) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NiFiUserGroup) DeepCopyInto(out *NiFiUserGroup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NiFiUserGroup.
func (in *NiFiUserGroup) DeepCopy() *NiFiUserGroup {
	if in == nil {
		return nil
	}
	out := new(NiFiUserGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NiFiUserGroup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NiFiUserGroupList) DeepCopyInto(out *NiFiUserGroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NiFiUserGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NiFiUserGroupList.
func (in *NiFiUserGroupList) DeepCopy() *NiFiUserGroupList {
	if in == nil {
		return nil
	}
	out := new(NiFiUserGroupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NiFiUserGroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NiFiUserGroupSpec) DeepCopyInto(out *NiFiUserGroupSpec) {
	*out = *in
	out.ClusterRef = in.ClusterRef
	if in.Users != nil {
		in, out := &in.Users, &out.Users
		*out = make([]UserGroupMember, len(*in))
		copy(*out, *in)
	}
	in.DriftPolicy.DeepCopyInto(&out.DriftPolicy)
	out.AdoptionPolicy = in.AdoptionPolicy
	out.Reconciliation = in.Reconciliation
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NiFiUserGroupSpec.
func (in *NiFiUserGroupSpec) DeepCopy() *NiFiUserGroupSpec {
	if in == nil {
		return nil
	}
	out := new(NiFiUserGroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NiFiUserGroupStatus) DeepCopyInto(out *NiFiUserGroupStatus) {
	*out = *in
	in.CommonStatus.DeepCopyInto(&out.CommonStatus)
	if in.MemberIDs != nil {
		in, out := &in.MemberIDs, &out.MemberIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NiFiUserGroupStatus.
func (in *NiFiUserGroupStatus) DeepCopy() *NiFiUserGroupStatus {
	if in == nil {
		return nil
	}
	out := new(NiFiUserGroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NiFiUserList) DeepCopyInto(out *NiFiUserList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NiFiUser, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NiFiUserList.
func (in *NiFiUserList) DeepCopy() *NiFiUserList {
	if in == nil {
		return nil
	}
	out := new(NiFiUserList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NiFiUserList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NiFiUserSpec) DeepCopyInto(out *NiFiUserSpec) {
	*out = *in
	out.ClusterRef = in.ClusterRef
	if in.Certificate != nil {
		in, out := &in.Certificate, &out.Certificate
		*out = new(UserCertificateSpec)
		**out = **in
	}
	in.DriftPolicy.DeepCopyInto(&out.DriftPolicy)
	out.AdoptionPolicy = in.AdoptionPolicy
	out.Reconciliation = in.Reconciliation
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NiFiUserSpec.
func (in *NiFiUserSpec) DeepCopy() *NiFiUserSpec {
	if in == nil {
		return nil
	}
	out := new(NiFiUserSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NiFiUserStatus) DeepCopyInto(out *NiFiUserStatus) {
	*out = *in
	in.CommonStatus.DeepCopyInto(&out.CommonStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NiFiUserStatus.
func (in *NiFiUserStatus) DeepCopy() *NiFiUserStatus {
	if in == nil {
		return nil
	}
	out := new(NiFiUserStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCISource) DeepCopyInto(out *OCISource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCISource.
func (in *OCISource) DeepCopy() *OCISource {
	if in == nil {
		return nil
	}
	out := new(OCISource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OwnershipPolicy) DeepCopyInto(out *OwnershipPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OwnershipPolicy.
func (in *OwnershipPolicy) DeepCopy() *OwnershipPolicy {
	if in == nil {
		return nil
	}
	out := new(OwnershipPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Parameter) DeepCopyInto(out *Parameter) {
	*out = *in
	if in.SensitiveValueFrom != nil {
		in, out := &in.SensitiveValueFrom, &out.SensitiveValueFrom
		*out = new(SensitivePropertySource)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Parameter.
func (in *Parameter) DeepCopy() *Parameter {
	if in == nil {
		return nil
	}
	out := new(Parameter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ParameterContextUpdateRequestStatus) DeepCopyInto(out *ParameterContextUpdateRequestStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ParameterContextUpdateRequestStatus.
func (in *ParameterContextUpdateRequestStatus) DeepCopy() *ParameterContextUpdateRequestStatus {
	if in == nil {
		return nil
	}
	out := new(ParameterContextUpdateRequestStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Position) DeepCopyInto(out *Position) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Position.
func (in *Position) DeepCopy() *Position {
	if in == nil {
		return nil
	}
	out := new(Position)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProcessGroupReference) DeepCopyInto(out *ProcessGroupReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProcessGroupReference.
func (in *ProcessGroupReference) DeepCopy() *ProcessGroupReference {
	if in == nil {
		return nil
	}
	out := new(ProcessGroupReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReconciliationPolicy) DeepCopyInto(out *ReconciliationPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReconciliationPolicy.
func (in *ReconciliationPolicy) DeepCopy() *ReconciliationPolicy {
	if in == nil {
		return nil
	}
	out := new(ReconciliationPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegistryFlowSource) DeepCopyInto(out *RegistryFlowSource) {
	*out = *in
	out.RegistryClientRef = in.RegistryClientRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegistryFlowSource.
func (in *RegistryFlowSource) DeepCopy() *RegistryFlowSource {
	if in == nil {
		return nil
	}
	out := new(RegistryFlowSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RevisionStatus) DeepCopyInto(out *RevisionStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RevisionStatus.
func (in *RevisionStatus) DeepCopy() *RevisionStatus {
	if in == nil {
		return nil
	}
	out := new(RevisionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RollbackStrategy) DeepCopyInto(out *RollbackStrategy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RollbackStrategy.
func (in *RollbackStrategy) DeepCopy() *RollbackStrategy {
	if in == nil {
		return nil
	}
	out := new(RollbackStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RolloutStrategy) DeepCopyInto(out *RolloutStrategy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RolloutStrategy.
func (in *RolloutStrategy) DeepCopy() *RolloutStrategy {
	if in == nil {
		return nil
	}
	out := new(RolloutStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeyRef) DeepCopyInto(out *SecretKeyRef) {
	*out = *in
	in.SecretKeySelector.DeepCopyInto(&out.SecretKeySelector)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeyRef.
func (in *SecretKeyRef) DeepCopy() *SecretKeyRef {
	if in == nil {
		return nil
	}
	out := new(SecretKeyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SensitivePropertySource) DeepCopyInto(out *SensitivePropertySource) {
	*out = *in
	if in.SecretKeyRef != nil {
		in, out := &in.SecretKeyRef, &out.SecretKeyRef
		*out = new(SecretKeyRef)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SensitivePropertySource.
func (in *SensitivePropertySource) DeepCopy() *SensitivePropertySource {
	if in == nil {
		return nil
	}
	out := new(SensitivePropertySource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SyncStatus) DeepCopyInto(out *SyncStatus) {
	*out = *in
	if in.LastAttemptTime != nil {
		in, out := &in.LastAttemptTime, &out.LastAttemptTime
		*out = (*in).DeepCopy()
	}
	if in.LastSuccessfulTime != nil {
		in, out := &in.LastSuccessfulTime, &out.LastSuccessfulTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SyncStatus.
func (in *SyncStatus) DeepCopy() *SyncStatus {
	if in == nil {
		return nil
	}
	out := new(SyncStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserCertificateSpec) DeepCopyInto(out *UserCertificateSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserCertificateSpec.
func (in *UserCertificateSpec) DeepCopy() *UserCertificateSpec {
	if in == nil {
		return nil
	}
	out := new(UserCertificateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserGroupMember) DeepCopyInto(out *UserGroupMember) {
	*out = *in
	out.UserRef = in.UserRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserGroupMember.
func (in *UserGroupMember) DeepCopy() *UserGroupMember {
	if in == nil {
		return nil
	}
	out := new(UserGroupMember)
	in.DeepCopyInto(out)
	return out
}
